##########################
#
# TITLE:        example_config.yaml
# DESCRIPTION:  Example configuration file
# AUTHOR:       Stefan Zdravkovic
# LINK:         https://www.github.com/histefanhere/quickscripts
#
##########################

# Specify the name of the computer/machine here.
# It is recommended that this is something unique!!
name: <COMPUTER NAME HERE>

# The path and filename of your scripts.yaml file where the program will fetch the quickscripts from.
# This can be relative to the code directory...
scripts: ./scripts.yaml
# Or it can be an absolute path from your root directory/drive
#scripts: /home/user/.scripts.yaml